version: "2.2"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
      - SPRING_PROFILES_ACTIVE=mysql
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
    - mysql
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
      - SPRING_PROFILES_ACTIVE=postgres
    profiles:
    - postgres
  spring-petclinic:
    build: 
      dockerfile: Dockerfile.multi
      args:
        - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    environment:
      JAR_FILE: target/*.jar
    depends_on:
      - mysql
    ports:
      - "8082:8080"
