# Dockerfile pre-built artifact
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app
# VOLUME /tmp - not important on this app

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
