# Ignore everything
*

# Allow files and directories
!/file.txt
!/src
!/target
!/.mvn
!mvnw
!pom.xml

# Ignore unnecessary files inside allowed directories
# This should go after the allowed directories
**/*~
**/*.log
**/.DS_Store
**/Thumbs.db
